### ISSUE TITLE
Trees scalable with terrain height

### ISSUE THREAD

**Issue by MikalDr** [Neelzee/Root#13]
This issue is not a mvp problem, but will make the games aesthetics look much better.
@Neelzee is on the case to my understanding. :-)

**Comment by Neelzee** [comment]
Fixed issue by implementing a script `TreeTiles` that contains a method for getting the specific Tile based on the Vector3Int position from the Tilemap, along with comments in `TreePlacer` in the `Update` function, where the Tile is being placed, on how to implement the new script.
